### PR TITLE
Greenkeeper/initial

### PR DESCRIPTION
**Pull request by charuhasan**

### CODE REVIEW

**Review by charuhasan — COMMENTED** [review]
Approved

**Comment by charuhasan** [comment]
Approved

**Comment by lissy93** [comment]
These changes are causing the CI tests to fail- will approve once all tests pass  😊

**Comment by lissy93** [comment]
Tests are failing because in line 8 of `package.json`
`"coverage": "istanbul report cobertura --dir output/coverage/jest"`
Should be:
`"coverage": "jest --coverage --coverageDirectory=output/coverage/jest"`
Error was introduced in e20631b318161c213ceab883cf74d01c4321f36c
Cannot merge until all tests pass.

**Pull request closed without merging**
